const tipsAndTricks = [
    { id: 100, category_name: "Anchoring", },
    { id: 200, category_name: "Antifouling", },
    { id: 300, category_name: "Bad Weather and conditions", },
    { id: 400, category_name: "Bags", },
    { id: 500, category_name: "Canvas", },
    { id: 600, category_name: "Charts And Guides", },
    { id: 700, category_name: "Clothing", },
    { id: 800, category_name: "Communication", },
    { id: 900, category_name: "Compass", },
    { id: 1000, category_name: "Deck & Cockpit", },
    { id: 1100, category_name: "Dinghies", },
    { id: 1200, category_name: "Docking", },
    { id: 1300, category_name: "Electric-AC", },
    { id: 1400, category_name: "Electric-DC", },
    { id: 1500, category_name: "Engine & Generators", },
    { id: 1600, category_name: "Fiberglass & Epoxy ", },
    { id: 1700, category_name: "Fishing", },
    { id: 1800, category_name: "Footwear", },
    { id: 1900, category_name: "Galley", },
    { id: 2000, category_name: "Head / Toilet", },
    { id: 2100, category_name: "Health Care", },
    { id: 2200, category_name: "Heating And Air-Conditioning", },
    { id: 2300, category_name: "Hose", },
    { id: 2400, category_name: "Interior", },
    { id: 2500, category_name: "Laundary", },
    { id: 2600, category_name: "Lights", },
    { id: 2700, category_name: "Maintenance", },
    { id: 2800, category_name: "Navigation", },
    { id: 2900, category_name: "Outboards", },
    { id: 3000, category_name: "Pets Aboard", },
    { id: 3100, category_name: "Plumbing", },
    { id: 3200, category_name: "Provisioning", },
    { id: 3300, category_name: "Refrigeration", },
    { id: 3400, category_name: "Rigging Running", },
    { id: 3500, category_name: "Rigging Standing", },
    { id: 3600, category_name: "Safety", },
    { id: 3700, category_name: "Scuba", },
    { id: 3800, category_name: "Snorkeling", },
    { id: 3900, category_name: "Tools", },
    { id: 4000, category_name: "Topside", },
    { id: 4100, category_name: "Ventilation", },
    { id: 4200, category_name: "Water Maker", },
    { id: 4300, category_name: "Water Sports", },
    { id: 4400, category_name: "Winterizing", },
    { id: 4500, category_name: "Zinc And Anodes", },
]

module.exports = tipsAndTricks